### ISSUE TITLE
[기능] Todo 완료 체크 API 연동

### ISSUE THREAD

**Issue by aemaaeng** [aemaaeng/wanted-pre-onboarding-frontend#11]
### Todos
- [x] Todo 체크박스 이벤트 할당
- [x] put 요청으로 `isCompleted` 부분만 수정 (안내 깃헙 2-3 updateTodo 참조)
- [x] 마찬가지로 서버에서 불러올 때 완료된 todo는 체크박스에 체크되어 있도록 하기
