### ISSUE TITLE
[기능] Todo 삭제

### ISSUE THREAD

**Issue by aemaaeng** [aemaaeng/wanted-pre-onboarding-frontend#12]
### Todos
- [x] Todo 수정, 삭제 버튼 만들기
- [x] 삭제 버튼 클릭 이벤트 할당
- [x] API 연동
- [x] 삭제된 todo는 화면에서 삭제하기
